# frozen_string_literal: true

module G18
  module Migration
    module Report
      module_function

      def render(result, source_dir:)
        all_invariants_ok = result.per_instance_edge_count == EXPECTED_RELATED_EDGES &&
                            result.unique_term_count == result.files_written.size
        checks = [
          ["#{result.unique_term_count} unique-term files written (one per distinct canonicalized term)", result.unique_term_count == result.files_written.size],
          ["#{result.per_instance_edge_count} per-instance VIM/VIML edges preserved on `publications[*].related` (expected #{EXPECTED_RELATED_EDGES})", result.per_instance_edge_count == EXPECTED_RELATED_EDGES],
          ["#{result.related_edge_count} distinct term-level edges (deduplicated superset in each term's `related`)", result.related_edge_count > 0],
        ]
        check_lines = checks.map { |label, ok| "- #{ok ? '✓' : '✗'} #{label}" }.join("\n")

        # Per-edition counts
        edition_lines = (result.editions || []).map do |e|
          "- #{e[:name]}#{e[:primary] ? ' (primary)' : ''}: #{e[:concept_count]} source concepts"
        end.join("\n")

        # ID conflicts per edition
        conflicts = result.id_conflicts || {}
        conflict_total = conflicts.values.sum(&:size)
        conflict_section =
          if conflicts.empty?
            "_(none)_"
          else
            conflicts.sort.map do |edition, list|
              <<~SEC
                ### #{edition} (#{list.size} conflicting IDs)

                Each ID below is assigned to multiple distinct concepts in the
                source publication. The dataset carries these as disambiguated
                suffixes (`<id>a`/`<id>b` in 2010, `<id>-RXXX-N` in 202X) but
                the underlying base number is genuinely shared and needs
                editorial reallocation.

                #{list.map { |c| "- `#{c[:id]}` ← #{c[:concepts].map { |x| "`#{x[:designation]}` (#{x[:source] || '—'}, raw `#{x[:raw_id]}`)" }.join(', ')}" }.join("\n")}
              SEC
            end.join("\n")
          end

        multi = result.multi_edge_terms
        collisions = result.slug_collisions
        collision_lines = collisions.empty? ? "_(none)_" : collisions.map do |c|
          "- `#{c[:slug]}` ← #{c[:terms].map { |t| "`#{t}`" }.join(", ")} (colliders get a `-<g18-id>` suffix)"
        end.join("\n")
        annotations = result.annotations_stripped || {}
        annotation_lines = annotations.empty? ? "_(none)_" : annotations.sort.map do |raw, cleaned|
          "- `#{raw}` → `#{cleaned}`"
        end.join("\n")
        merges = result.alias_merges || {}
        merge_lines = merges.empty? ? "_(none)_" : merges.sort.map do |canonical, variants|
          "- `#{canonical}` ← #{variants.map { |v| "`#{v}`" }.join(", ")}"
        end.join("\n")

        <<~MD
          # Migration Report

          Generated by `<repo>/scripts/migrate_from_vocab.rb` against
          `#{source_dir}`.

          ## Editions consumed

          #{edition_lines.empty? ? "_(none)_" : edition_lines}

          ## Counts

          | Metric | Value |
          |---|---|
          | Total source entries parsed | #{result.instance_count} |
          | Unique-term files written | #{result.files_written.size} |
          | Distinct canonicalized terms | #{result.unique_term_count} |
          | Total publication instances (sum of `publications[]`) | #{result.instance_count} |
          | Per-instance VIM/VIML edges preserved (`publications[*].related`) | #{result.per_instance_edge_count} |
          | Distinct term-level edges (each term's `related`, deduplicated) | #{result.related_edge_count} |
          | Designation annotations stripped | #{annotations.size} |
          | Alias merges applied | #{merges.size} |
          | ID conflicts across editions | #{conflict_total} |

          ## Invariants

          #{check_lines}

          > Note: the SOURCE_INSTANCE_COUNT invariant was relaxed when we
          > added multi-edition support (2010 + 202X). The migration now
          > preserves all source concepts across all editions; the count
          > grows as new editions are added.

          ## ID conflicts (#{conflict_total} across #{conflicts.size} editions)

          IDs in the source publication that are reused for two or more
          distinct concepts. Editors (TC 1) must decide whether the concepts
          are truly distinct (split via `<id>a` / `<id>b`) or represent a
          single concept (merge).

          #{conflict_section}

          ## Designation annotations stripped (#{annotations.size})

          Source designations sometimes include trailing editorial notes in
          square brackets (VIM citations, scope restrictions, footnote
          markers). The migration strips these before grouping so the term
          merges with its canonical form. Parentheses are preserved (they
          hold legitimate symbol abbreviations like `(Max)`, `(MPE)`).

          #{annotation_lines}

          ## Alias merges (#{merges.size})

          Editorial variants merged via `tc-sc/term-aliases.yaml`. Extend
          that file to handle additional singular/plural or other variants.

          #{merge_lines}

          ## Multi-edge terms (#{multi.size})

          Terms whose instances reference more than one VIM/VIML concept. The
          first edge (lowest G 18 identifier, then dedup order) populates
          `data.official_concept`; all edges are preserved under `related`.

          #{multi.empty? ? "_(none)_" : multi.map { |k| "- `#{k}`" }.join("\n")}

          ## Slug collisions (#{collisions.size})

          Distinct canonicalized terms whose slugified form collides. The
          alphabetically-first term keeps the bare slug; subsequent colliders
          get a `-<g18-id>` suffix so every term gets its own file. Editors
          should review these and consider adding alias entries when the
          variants represent the same concept.

          #{collision_lines}

          ## Source data integrity

          The vocabulary repo's `datasets/g18-*` directories are read-only
          from this script's perspective — they are **never modified**.
          Re-running this migration regenerates `data/` deterministically.
        MD
      end
    end
  end
end
