# frozen_string_literal: true

require_relative "migration"

module G18
  module Migration
    module Report
      module_function

      def render(result, source_dir:)
        all_invariants_ok = result.instance_count == SOURCE_INSTANCE_COUNT &&
                            result.per_instance_edge_count == EXPECTED_RELATED_EDGES &&
                            result.unique_term_count == result.files_written.size
        checks = [
          ["Sum of publications[] = #{SOURCE_INSTANCE_COUNT} (no instances lost)", result.instance_count == SOURCE_INSTANCE_COUNT],
          ["#{result.unique_term_count} unique-term files written (one per distinct canonicalized term)", result.unique_term_count == result.files_written.size],
          ["#{result.per_instance_edge_count} per-instance VIM/VIML edges preserved on `publications[*].related` (expected #{EXPECTED_RELATED_EDGES})", result.per_instance_edge_count == EXPECTED_RELATED_EDGES],
          ["#{result.related_edge_count} distinct term-level edges (deduplicated superset in each term's `related`)", result.related_edge_count > 0],
        ]
        check_lines = checks.map { |label, ok| "- #{ok ? '✓' : '✗'} #{label}" }.join("\n")
        multi = result.multi_edge_terms
        collisions = result.slug_collisions
        collision_lines = collisions.empty? ? "_(none)_" : collisions.map do |c|
          "- `#{c[:slug]}` ← #{c[:terms].map { |t| "`#{t}`" }.join(", ")} (colliders get a `-<g18-id>` suffix)"
        end.join("\n")
        annotations = result.annotations_stripped || {}
        annotation_lines = annotations.empty? ? "_(none)_" : annotations.sort.map do |raw, cleaned|
          "- `#{raw}` → `#{cleaned}`"
        end.join("\n")
        merges = result.alias_merges || {}
        merge_lines = merges.empty? ? "_(none)_" : merges.sort.map do |canonical, variants|
          "- `#{canonical}` ← #{variants.map { |v| "`#{v}`" }.join(", ")}"
        end.join("\n")
        <<~MD
          # Migration Report

          Generated by `<repo>/scripts/migrate_from_vocab.rb` against
          `#{source_dir}`.

          ## Counts

          | Metric | Value |
          |---|---|
          | Source entries parsed | #{SOURCE_INSTANCE_COUNT} |
          | Unique-term files written | #{result.files_written.size} |
          | Distinct canonicalized terms | #{result.unique_term_count} |
          | Total publication instances (sum of `publications[]`) | #{result.instance_count} |
          | Per-instance VIM/VIML edges preserved (`publications[*].related`) | #{result.per_instance_edge_count} |
          | Distinct term-level edges (each term's `related`, deduplicated) | #{result.related_edge_count} |
          | Designation annotations stripped | #{annotations.size} |
          | Alias merges applied | #{merges.size} |

          ## Invariants (TODO 02 acceptance)

          #{check_lines}

          Overall: **#{all_invariants_ok ? 'PASS' : 'FAIL'}**.

          > The TODO 02 acceptance line "All 101 VIM/VIML cross-refs preserved
          > (counted across new files)" is satisfied by counting edges across
          > every `publications[*].related` block: each source instance that
          > asserted a `see` edge contributes one entry to its publication's
          > `related` array, so the total matches the source's 101. The
          > term-level `related` array is the deduplicated superset — useful
          > for browsing, but the per-instance edges are kept too for full
          > traceability.

          ## Designation annotations stripped (#{annotations.size})

          Source designations sometimes include trailing editorial notes in
          square brackets (VIM citations, scope restrictions, footnote
          markers). The migration strips these before grouping so the term
          merges with its canonical form. Parentheses are preserved (they
          hold legitimate symbol abbreviations like `(Max)`, `(MPE)`).

          #{annotation_lines}

          ## Alias merges (#{merges.size})

          Editorial variants merged via `tc-sc/term-aliases.yaml`. Extend
          that file to handle additional singular/plural or other variants.

          #{merge_lines}

          ## Multi-edge terms (#{multi.size})

          Terms whose instances reference more than one VIM/VIML concept. The
          first edge (lowest G 18 identifier, then dedup order) populates
          `data.official_concept`; all edges are preserved under `related`.

          #{multi.empty? ? "_(none)_" : multi.map { |k| "- `#{k}`" }.join("\n")}

          ## Slug collisions (#{collisions.size})

          Distinct canonicalized terms whose slugified form collides. The
          alphabetically-first term keeps the bare slug; subsequent colliders
          get a `-<g18-id>` suffix so every term gets its own file. Editors
          should review these and consider adding alias entries when the
          variants represent the same concept.

          #{collision_lines}

          ## Source data integrity

          The vocabulary repo's `datasets/g18/` is read-only from this script's
          perspective — it is **never modified**. Re-running this migration
          regenerates `data/` deterministically: UUIDs are v5-style hashes of
          the canonicalized term name, so the same source + aliases always
          yields the same output.
        MD
      end
    end
  end
end
